FROM ubuntu

RUN apt-get update; \
    apt-get install -y \
                    check \
                    clang-format \
                    clang-tidy \
                    cmake \
                    cppcheck \
                    gcc \ 
                    gdb \
                    git \
                    make \
                    valgrind \
                    vim \
                    pkg-config \
                    pip; \
                      pip install gcovr
